# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

# Jekyll 基本设置
title: Earth_zZ                    # 网站标题
description: 初学者的博客             # 网站描述
url: "https://earth0718.github.io" # 你的网站 URL
baseurl: ""                    # 如果网站在子目录，则设置为 "/你的子目录名"

# 用户信息
author: earth0718                # 你的名字或昵称 (根据 GitHub 用户名推断，可修改)
avatar: /assets/images/picture.jpg # 你的头像图片路径
# bio: "Your Bio"                 # 你的简介 (可选)
# email: "your-email@example.com" # 你的邮箱 (可选)

# 构建设置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge     # 代码高亮设置 (Chirpy 常用)
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 插件 (保留你的设置，并添加 Chirpy 常用插件)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives           # Chirpy 用于生成分类和标签页面
  - jekyll-paginate           # 用于分页

# 主题 (如果你通过 Gem 安装了主题，可以取消注释下一行)
# theme: jekyll-theme-chirpy

# -----------------------------------------------------------------------------
# 主题 (Chirpy) 特有设置
# -----------------------------------------------------------------------------

# 语言和时区
lang: zh-CN                    # 网站语言 (根据描述推断)
timezone: Asia/Shanghai        # 你的时区 (示例，请根据你的实际位置修改)

# 社交链接 (可选，示例)
social:
  # name: GitHub
  # icon: fab fa-github
  # link: https://github.com/earth0718
  # name: Twitter
  # icon: fab fa-twitter
  # link: https://twitter.com/username
  # ... 其他社交链接
  # name: RSS
  # icon: fas fa-rss
  # link: /feed.xml

# 评论系统设置
comments:
  provider: hyvor              # 指定使用 Hyvor Talk
  hyvor:
    website_id: 13109 # !!! 重要：请替换成你自己的 Hyvor Website ID !!!

# 分页设置
paginate: 10                   # 每页显示的文章数量
paginate_path: /page/:num/

# 分类和标签页面的 URL 结构 (配合 jekyll-archives)
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category         # 使用 _layouts/category.html 布局
    tag: tag                   # 使用 _layouts/tag.html 布局
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# 目录 (Table of Contents)
toc:
  enabled: true
  h_min: 1                     # 显示的最小标题级别 (e.g., h1)
  h_max: 4                     # 显示的最大标题级别 (e.g., h4)
  skip_no_toc_section: false   # 是否跳过没有目录的文章中的TOC部分

# 资源压缩与缓存 (Chirpy 推荐)
assets:
  self_host:
    enabled: true              # 将 JS/CSS 资源本地化

# 默认 Front Matter (为所有文章和页面设置默认布局等)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true           # 默认开启文章评论
      toc: true                # 默认开启文章目录
      # image: # 可以为文章设置默认封面图
      #   path: /path/to/default/image.jpg
      #   alt: Default post image
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      # comments: true # 如果希望页面也默认开启评论，取消此行注释
      # toc: true      # 如果希望页面也默认开启目录，取消此行注释

# Sass/SCSS 编译设置
sass:
  sass_dir: /_sass
  style: compressed # 输出压缩后的 CSS

# 排除文件/文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor/
  - node_modules/
  - .idea/
  - .gitignore

# -----------------------------------------------------------------------------
# End of Configuration
# -----------------------------------------------------------------------------
